name: Deploy test

on:
  pull_request:
    branches: [ "Master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v2

    - name: Deploy test
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test